import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import React from "react";
import { embedDashboard } from "@superset-ui/embedded-sdk";
import axios from "axios";

export default function Home() {
  const [csrf, setCsrf] = React.useState();

  const getToken = async () => {
    const response = await axios.get(`http://localhost:3731/guest-token`);
    const tokens = await response.data;
    setCsrf(tokens.csrfToken);
    console.log("response headers", response);
    return tokens.token;
  };

  useEffect(() => {
    const embed = async () => {
      await embedDashboard({
        id: "8b8c4fde-8336-490c-84e2-001a7f2f9b02", // given by the Superset embedding UI
        supersetDomain: "https://ss.acruxtek.net/",
        mountPoint: document.getElementById("dashboard"), // html element in which iframe render
        fetchGuestToken: () => getToken(),
        dashboardUiConfig: {
          hideTitle: true,
          hideChartControls: true,
          hideTab: true,
        },
        filters: {
          expanded: true,
        },
        headers: {
          "X-CSRF-TOKEN": csrf,
        },
      });
    };
    if (document.getElementById("dashboard")) {
      embed();
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="App">
        <h1>Superset Dashboard </h1>
        <div style={{ width: "800px", height: "800px" }} id="dashboard" />
      </main>
    </>
  );
}
